In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Create arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)                      # np.full is a handy NumPy function used to create a new array of a specified shape filled with a constant value.

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,5,10])                  # coverting python list into array
a

array([ 1,  2,  5, 10])

In [8]:
a[2]                                      # accessing numbers in array (index start with 0)

np.int64(5)

In [9]:
a[0]

np.int64(1)

In [12]:
a[0] = 20
a

array([20,  2,  5, 10])

In [13]:
np.arange(10)                            # creates a range of 10 from 0 to 9 by default and 10 is exclusive

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3, 10)                         # if we dont want from 0 we need to specify and 10 is exclusive so it will go till 9

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 11)                   #It creates 11 numbers evenly spaced between 0 and 100, inclusive.

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional arrays

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [19]:
n[0, 1]                                                  # accessing row 0 col 1

np.int64(2)

In [21]:
n[0, 1] = 20                                             # assigning new value
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[0]                                  # if we want o full 0th row

array([ 1, 20,  3])

In [24]:
n[:, 1]                            # if we want 1st col for all rows

array([20,  5,  8])

In [25]:
n[:]                                # : means all rows

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
n[2] = [1, 1, 1]                   # asssigning new values to 3rd row
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [28]:
n[:, 1] = [0, 0, 0]                # assigning new values to 2nd col of all rows
n

array([[1, 0, 3],
       [4, 0, 6],
       [1, 0, 1]])

# Randomly generated arrays

In [29]:
np.random.rand(5, 2)

array([[0.00759397, 0.48632223],
       [0.46469588, 0.0201453 ],
       [0.67353797, 0.65004811],
       [0.31791927, 0.5280887 ],
       [0.4597573 , 0.66370964]])

In [30]:
np.random.seed(2)      # np.random.seed() is used to control randomness in NumPy — especially when you're generating random numbers — so that your results are reproducible.
np.random.rand(5,2)    # Run it again with the same seed? You’ll get the same output.Change the seed, or remove it, and you'll get different numbers.

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [31]:
np.random.seed(2) 
np.random.randn(5,2)   # np.random.randn(5, 2) means: Generate a 5×2 array, Values are from the standard normal distribution, i.e., mean = 0, standard deviation = 1, The values can be positive or negative, They follow a bell curve (normal distribution)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [32]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5, 2))  #Generates a 5×2 NumPy array of random integers. Each integer is ≥ 0 (inclusive)and < 100 (exclusive).So values will be from 0 to 99 (inclusive)

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element wise operations

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
a + 1           # adds 1 to every elemt of array

array([1, 2, 3, 4, 5])

In [35]:
a * 2              # multiply 2 to every element and we can -, /

array([0, 2, 4, 6, 8])

In [36]:
b = 10 + (a * 100)    # chaining: multiplying with 100 and adding 10 to every elemt of a and assigning to b
b

array([ 10, 110, 210, 310, 410])

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a + b

array([ 10, 111, 212, 313, 414])

# Comparison operations

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a >= 2                  # tells us which elements satisy the condn.

array([False, False,  True,  True,  True])

In [41]:
b

array([ 10, 110, 210, 310, 410])

In [42]:
b[1] = 0
b

array([ 10,   0, 210, 310, 410])

In [43]:
a > b

array([False,  True, False, False, False])

In [44]:
a[a > b]           # which elements of a are greater than element of b

array([1])

# Summarizing operations

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.min()

np.int64(0)

In [47]:
a.max()

np.int64(4)

In [48]:
a.sum()      # sum of all arrays

np.int64(10)

In [49]:
a.mean()

np.float64(2.0)

In [50]:
a.std()      # standard deviation

np.float64(1.4142135623730951)

In [51]:
n

array([[1, 0, 3],
       [4, 0, 6],
       [1, 0, 1]])

In [52]:
n.mean()

np.float64(1.7777777777777777)