In [1]:
import numpy as np

# Vector-Vector Multiplication

In [25]:
u = np.array([1, 2, 3])

v = np.array([4, 5, 6])

In [26]:
u.shape, v.shape

((3,), (3,))

In [27]:
u.shape[0], v.shape[0]

(3, 3)

In [28]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]                   # ensure shapes match

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]    # dot product of each row pair

    return result

In [29]:
vector_vector_multiplication(u, v)

np.float64(32.0)

In [40]:
u.dot(v)                             # Numpy inbuilt function

np.int64(50)

# Matrix-Vector Multiplication

In [31]:
U = np.array([
    [1, 2, 3],                                 # Capital U denotes matrix and small u denotes vector and same for v
    [4, 5, 6]
])
                                        
v = np.array([7, 8, 9])

In [32]:
U

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
U.shape , v.shape

((2, 3), (3,))

In [34]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [35]:
matrix_vector_multiplication(U, v)

array([ 50., 122.])

In [41]:
U.dot(v)                              # Numpy inbuilt function

array([ 50, 122])

# Matrix-Matrix Multiplication

In [42]:
U = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

V = np.array([
    [1, 4],
    [2, 5],
    [3, 6]
])

In [43]:
U.shape, V.shape

((2, 3), (3, 2))

In [44]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows , num_cols))

    for i in range(num_cols):
        vi = V[ :, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[ :, i] = Uvi

    return result
    

In [45]:
matrix_matrix_multiplication(U, V)

array([[14., 32.],
       [32., 77.]])

In [47]:
U.dot(V)                              #Numpy in built function

array([[14, 32],
       [32, 77]])

# Identity Matrix

In [54]:
I = np.eye(2)   
I

array([[1., 0.],
       [0., 1.]])

In [55]:
V

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
V.dot(I)                              # Any matrix * I = Matrix (it should have same dimensions)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

# Inverse

In [60]:
A = np.array([
    [1, 2, 3],                             # Need square matrix for inverse
    [0, 1, 4],                             # A matrix is invertible (has an inverse) only if its determinant is non-zero.                                      
    [5, 6, 0]                              # Inverse of matrix * matrix = I
]) 

In [62]:
A_inv = np.linalg.inv(A)
A_inv

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [64]:
A_inv.dot(A)                                #8.88e-16 ≈ 0 — it’s less than one quadrillionth, so it’s negligible.

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -8.8817842e-16,  1.0000000e+00]])

In [65]:
np.round(A_inv.dot(A), decimals=10)


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])